### ISSUE TITLE
TextParser und PaginateController - Fehler

### ISSUE THREAD

**Issue by AlexSanFa** [AgenturPottkinder/typo3_forum#251]
Sehr geehrte Damen und Herren,

Ich setze eine TYPO3-Website (7.6.26) mit der Extension typo3_forum (1.1.0) um. Das ist eine schöne Extension mit vielen Funktion - vielen Dank für die großartige Arbeit! 

Allerdings habe ich ein kleines Problem, dass ich nicht lokalisieren und beheben kann. Beim Absenden einer neuen Antwort zu einem Thema im Forum kommt eine Fehlermeldung: 'Validation failed while trying to call TYPO3\CMS\Fluid\ViewHelpers\Widget\Controller\PaginateController->indexAction()'.

Es kommen folgende Fehler:

LIVE FEHLER Fehlerbehandlung Core: Error handler (FE): PHP Warning: include(): Failed opening '../../../Resources/Private/Libraries/GeSHi/geshi.php' for inclusion (include_path='/html/vendor/pear/pear_exception:/html/vendor/pear/http_request2:.:') in /html/typo3conf/ext/typo3_forum/Classes/TextParser/Service/AbstractGeshiService.php line 4 

LIVE FEHLER Fehlerbehandlung Core: Error handler (FE): PHP Warning: include(../../../Resources/Private/Libraries/GeSHi/geshi.php): failed to open stream: No such file or directory in /html/typo3conf/ext/typo3_forum/Classes/TextParser/Service/AbstractGeshiService.php line 4 

LIVE FEHLER Fehlerbehandlung Core: Error handler (FE): PHP Warning: Division by zero in /html/typo3conf/ext/typo3_forum/Classes/Domain/Model/Forum/Topic.php line 308

Könnten Sie mir helfen und sagen, woran das Problem liegen kann?

Vielen Dank und freundliche Grüße

**Comment by Avalarion** [comment]
Hey @AlexSanFa,

bitte versuch hier beim Englischen zu bleiben.

Ich vermute, dass nach 2,5 Jahren dein Problem nicht mehr Akut ist, daher werde ich das Ticket schließen, wenn du hier noch Hilfe brauchst, schreib einfach einen Kommentar und ich öffne das Ticket erneut.

Hab einen schönen Tag,

Bastian

===

Hey @AlexSanFa,

please stay in english =).

I guess that after 2,5 years your issue is not a problem anymore. If I am wrong please write a comment so I am reopening this closed ticket.

Have a nice day,

Bastian
